name: CI for Vertix Contracts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Cache Foundry dependencies
      - name: Cache Foundry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            out
            cache
            lib
          key: foundry-${{ hashFiles('foundry.toml', 'remappings.txt', 'Makefile') }}
          restore-keys: |
            foundry-

      # Install dependencies using Makefile
      - name: Install dependencies
        run: make install

      # Build contracts
      - name: Build contracts
        run: make build

      # Run tests
      - name: Run tests
        run: make test

  deploy-anvil:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Cache Foundry dependencies
      - name: Cache Foundry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            out
            cache
            lib
          key: foundry-${{ hashFiles('foundry.toml', 'remappings.txt', 'Makefile') }}
          restore-keys: |
            foundry-

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Start Anvil in the background
      - name: Start Anvil
        run: anvil --block-time 1 &
        env:
          ANVIL_RPC_URL: http://127.0.0.1:8545
          ANVIL_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

      # Deploy to Anvil
      - name: Deploy to Anvil
        run: make deploy ARGS="--network anvil"
        env:
          ANVIL_RPC_URL: http://127.0.0.1:8545
          ANVIL_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

  # deploy-sepolia:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   environment: sepolia-deployment

  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     # Set up Foundry
  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     # Cache Foundry dependencies
  #     - name: Cache Foundry dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.foundry
  #           out
  #           cache
  #           lib
  #         key: foundry-${{ hashFiles('foundry.toml', 'remappings.txt', 'Makefile') }}
  #         restore-keys: |
  #           foundry-

  #     # Install dependencies
  #     - name: Install dependencies
  #       run: make install

  #     # Deploy to Sepolia
  #     - name: Deploy to Sepolia
  #       run: make deploy ARGS="--network sepolia"
  #       env:
  #         SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  #         PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  #         ETHERSCAN_API_URL: ${{ secrets.ETHERSCAN_API_URL }}